spring:
  application:
    name: demo-modulith
  datasource:
    username: user
    password: Test1234=
    url: jdbc:postgresql://localhost:5432/modulith
  jpa:
    hibernate:
      ddl-auto: create
